apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "siglo-xxi", "namespace": "", "kind": "DeploymentConfig"}]'
    name: pipeline-siglo-xxi
  spec:
    source:
      git:
        ref: pipeline
        uri: https://apps-assist.com.co:8443/gitlab/demo-assist-docker/siglo-xxi.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
      type: Generic