apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: assist
  name: assist
spec:
  output:
    to:
      kind: ImageStreamTag
      name: assist:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/Andresado/15334783.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: assist-webserver:latest
        namespace: weepee-registry
    type: Docker
